version: '2'
services:
    keken2-app:
        image: keken2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://keken2-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=keken2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    keken2-mongodb:
        extends:
            file: mongodb.yml
            service: keken2-mongodb
